FROM bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0

#COPY ./message_families .
#RUN pip install ./audit_proof
RUN pip3 install --no-cache-dir "git+https://github.com/ianco/aca-py-audit-plugin.git@master#egg=aca-py-audit-plugin&subdirectory=message_families/audit_proof"

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
